spring.application.name=myapp

server.port=8080

spring.datasource.url=jdbc:mysql://localhost:3306/myappdb
spring.datasource.username=root
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update

spring.thymeleaf.cache=false
